name: Shopkeepers
version: '${project.version}'
description: Custom villager shopkeepers
author: nisovin
website: http://dev.bukkit.org/server-mods/shopkeepers/
softdepend: [Multiverse-Core, My Worlds, Transporter, Citizens]

main: com.nisovin.shopkeepers.ShopkeepersPlugin

commands:
    shopkeeper:
        description: Base for all shopkeeper commands.
        aliases: [shopkeepers]
        usage: 'Unknown command! Try /<command> help'

permissions:
    shopkeeper.trade:
        description: Trade with any shopkeeper
        default: true
    shopkeeper.reload:
        description: Reloads the plugin
        default: op
    shopkeeper.debug:
        description: Toggles debug mode
        default: op
    shopkeeper.bypass:
        description: Bypass player shop restrictions
        default: op
    shopkeeper.transfer:
        description: Transfer ownership of a shopkeeper
        default: op
    shopkeeper.setforhire:
        description: Set a shopkeeper to be for hire
        default: op
    shopkeeper.hire:
        description: Hire a shopkeeper
        default: true
    shopkeeper.remote:
        description: Trade with a remote admin shop by name
        default: false
        
    shopkeeper.admin:
        description: Create and modify admin shopkeepers
        default: op
    shopkeeper.player:
        description: Create and modify any player shopkeeper
        default: false
        children:
            shopkeeper.player.normal: true
            shopkeeper.player.book: true
            shopkeeper.player.buy: true
            shopkeeper.player.trade: true
    shopkeeper.player.normal:
        description: Create and modify normal player shopkeepers
        default: true
    shopkeeper.player.book:
        description: Create and modify book player shopkeepers
        default: true
    shopkeeper.player.buy:
        description: Create and modify buying player shopkeepers
        default: true
    shopkeeper.player.trade:
        description: Create and modify trading player shopkeepers
        default: true

    shopkeeper.sign:
        description: Create sign shopkeepers
        default: true
    shopkeeper.citizen:
        description: Create citizens shopkeepers
        default: op
    shopkeeper.entity.*:
        description: Create shopkeepers of all entity types
        default: op

    shopkeeper.villager:
        description: Create villager shopkeepers
        default: true
        children:
            shopkeeper.entity.villager: true
    shopkeeper.witch:
        description: Create witch shopkeepers
        default: true
        children:
            shopkeeper.entity.witch: true
    shopkeeper.creeper:
        description: Create creeper shopkeepers
        default: true
        children:
            shopkeeper.entity.creeper: true
